### ISSUE TITLE
Specify UUID length?

### ISSUE THREAD

**Issue by JosiahParry** [radim10/short-uuid#2]
One of the benefits of the short-uuid JS implementation is that you can specify the length of the returned UUID. It would be really great if the same was possible with this library

**Comment by radim10** [comment]
I agree with that. Will implement it soon.

**Comment by radim10** [comment]
> One of the benefits of the short-uuid JS implementation is that you can specify the length of the returned UUID. It would be really great if the same was possible with this library

How is it possible to specify the length of returned UUID? Shouln't UUID have always the same length (using the same encoding)?

**Comment by JosiahParry** [comment]
See https://shortunique.id/
I am unsure how it works there is not any documentation for the library 

<img width="490" alt="image" src="https://github.com/user-attachments/assets/c1b39f4c-b516-4f87-8abc-9728f4bf00b6">

**Comment by radim10** [comment]
> See https://shortunique.id/ I am unsure how it works there is not any documentation for the library
> <img alt="image" width="490" src="https://private-user-images.githubusercontent.com/13534508/358861531-c1b39f4c-b516-4f87-8abc-9728f4bf00b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTkzMzgsIm5iZiI6MTcyMzkxOTAzOCwicGF0aCI6Ii8xMzUzNDUwOC8zNTg4NjE1MzEtYzFiMzlmNGMtYjUxNi00Zjg3LThhYmMtOTcyOGY0YmYwMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE4MjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMmRjNTg1NGEwMmE1MzViZDY0OGFlYTkzM2E3MTAzYjIzOTU0YTAzNWIyZmQ1NWNlOWYwNTRlMDE5OGZkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C-qQf0bGo6DRndSSYv91bqbi2ij0tUxwE7xminuoRDI">
> 
> See also the `ShortUniqueIdOptions` interface https://shortunique.id/interfaces/ShortUniqueIdOptions.html
This look more like a random Id generator like crypto or nanoid in js. It look like it does not offer translation from or to UUID.

**Comment by radim10** [comment]
> See https://shortunique.id/ I am unsure how it works there is not any documentation for the library
> <img alt="image" width="490" src="https://private-user-images.githubusercontent.com/13534508/358861531-c1b39f4c-b516-4f87-8abc-9728f4bf00b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTk2ODUsIm5iZiI6MTcyMzkxOTM4NSwicGF0aCI6Ii8xMzUzNDUwOC8zNTg4NjE1MzEtYzFiMzlmNGMtYjUxNi00Zjg3LThhYmMtOTcyOGY0YmYwMGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE4Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhYTdlM2Y4ZWFjODc5MzU2NmFmYTU1ZjE4NjJkYTkwNjI1ODllN2Y2ODcwMjZkYWQ1MmZhNmFhNWE3NTZlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n4y4mVnnnRswciIr9Qxmv5O4_veddYeJ9kO8lT1usOc">
> 
> See also the `ShortUniqueIdOptions` interface https://shortunique.id/interfaces/ShortUniqueIdOptions.html

This look more like a random Id generator like crypto or nanoid in js. It look like it does not offer translation from or to UUID.
